apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    app: mysite
spec:
  containers:
  - name: mysite
    image: ghcr.io/25542554/cis-92-devbox:main
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 256m 
        memory: 250Mi
    livenessProbe:
      httpGet:
        path: /polls/
        port: 8000
    ports:
    - containerPort: 8000
    env:
    - name: DB_ENGINE
      value: "sqlite"
    - name: DJANGO_ADMIN_EMAIL
      value: "test@test.test"
    - name: DJANGO_ADMIN_USERNAME
      value: "test"
    - name: DJANGO_SUPERUSER_PASSWORD
      value: "test"